[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "day5"
version = "0.1.0"
description = "Day 5 Streamlit App"
license = { text = "MIT" }
authors = [{ name = "galleon", email = "guillaume.alleon@gmail.com" }]
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["."]
